### ISSUE TITLE
__builtin_is_constant_evaluated doesn't exist in VS2017

### ISSUE THREAD

**Issue by archo5** [vitaut/zmij#141]
when building zmij.cc for x64 with VS2017:

```
zmij.cc(264): error C3861: '__builtin_is_constant_evaluated': identifier not found
zmij.cc(443): error C2131: expression did not evaluate to a constant
zmij.cc(264): note: a non-constant (sub-)expression was encountered
```

issue seems to have been introduced in https://github.com/vitaut/zmij/pull/48

the relevant block of code probably just needs to be wrapped in `#ifdef __cpp_lib_is_constant_evaluated`, like in the other spot at line 144

that's what I did locally but since I only use VS2017, I can't verify that it'll produce the intended outcome for everyone else

**Comment by vitaut** [comment]
You are right, it should be wrapped in `__builtin_is_constant_evaluated`. A PR is welcome!
