### PR TITLE
Allow building with older gcc

### PR DESCRIPTION
**Pull request by patrickbkr**
This change fixes zmij to build on older gcc. Without this patch it fails to build on at least gcc 6.3.0 and 5.3.1. This is the error:

    zmij.c:1118:42: error: initializer element is not constant
    #define ZMIJ_SPLAT64(x) {(long long)(x), (long long)(x)}
                                             ^

### CODE REVIEW

**Comment by vitaut** [comment]
Thank you
